accounts/urls.py
from django.conf.urls import url

from accounts.views import (
    CustomUserCreateView,
    CustomUserLoginView,
    LogoutView,
    UserConnectionsView
)

urlpatterns = [
    url(r'^register/', CustomUserCreateView.as_view(), name='register'),
    url(r'^login/', CustomUserLoginView.as_view(), name='login'),
    url(r'^connections/', UserConnectionsView.as_view(), name='connections'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
]

api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    url(r'^program/$', views.ProgramListView.as_view(), name='list-program'),
    url(r'^program/(?P<pk>[0-9]+)/$', views.ProgramRetrieveView.as_view(), name='retrieve-program'),
]

integrations/salesforce/urls.py
from django.conf.urls import url
from integrations.salesforce import views


urlpatterns = [
    url(r'^delete/$', views.DeleteSalesforceConnectionView.as_view(), name='delete_salesforce'),
]

program_manager/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from program_manager import views


urlpatterns = [
    url(r'^$', views.ProgramListView.as_view(), name='program_list'),
    url(r'^dash/$', views.ProgramDashboardView.as_view(), name='program_dash'),
    url(r'^select_program_type/(?P<pk>[0-9]+)$', views.ProgramSelectType.as_view(), name='select_program_type_pk'),  # TODO: remove
    url(r'^analysis_select/$', login_required(TemplateView.as_view(template_name='program_manager/analysis_select.html')), name='analysis_select'),
    url(r'^analysis_confirm/$', login_required(TemplateView.as_view(template_name='program_manager/analysis_confirm.html')), name='analysis_confirm'),
    url(r'^batch_select/$', views.ProgramAddFiltersView.as_view(), name='batch_select'),
    url(r'^select_actions/(?P<pk>[0-9]+)$', views.ProgramSelectActionsView.as_view(), name='select_actions'),
    url(r'^fieldfilter/(?P<pk>[0-9]+)/delete', views.DeleteFieldFilterView.as_view(), name='delete_fieldfilter'),
    url(r'^import_select/$', views.CreateListImportProgramView.as_view(), name='import_select'),
    url(r'^import_program/(?P<pk>[0-9]+)/$', views.ListImportProgramView.as_view(), name='import_program_details'),
    url(r'^count_data/(?P<pk>[0-9]+)/$', views.count_data, name='count_data'),
    url(r'^download_database/$', views.DownloadDatabaseView.as_view(), name='download_database'),
    url(r'^job_status$', views.JobStatusView.as_view(), name='job_status'),
    url(r'^program_action/$', views.ProgramActionView.as_view(), name='program_action'),
    url(r'^program_set_tags/', views.program_set_tags, name='program_set_tags'),

    url(r'^program/details/(?P<pk>[-\w]+)/$', views.ProgramDetailsView.as_view(), name='program_details'),
    url(r'^program/(?P<pk>[0-9]+)/analyse/$', views.ProgramAnalyseView.as_view(), name='analyse_program'),
    url(r'^program/(?P<pk>[0-9]+)/optimize/$', views.ProgramOptimizeView.as_view(), name='optimize_program'),
    url(r'^program/(?P<pk>[0-9]+)/pause/$', views.ProgramPauseView.as_view(), name='pause_program'),
    url(r'^program/(?P<pk>[0-9]+)/cancel/$', views.ProgramCancelView.as_view(), name='cancel_program'),
    url(r'^program/(?P<pk>[0-9]+)/archive/$', views.ProgramArchiveView.as_view(), name='archive_program'),
    url(r'^program/(?P<pk>[0-9]+)/reactivate/$', views.ProgramReactivateView.as_view(), name='reactivate_program'),
    url(r'^program/(?P<pk>[0-9]+)/rename/$', views.ProgramSetNameView.as_view(), name='rename_program'),
    url(r'^program/(?P<pk>[0-9]+)/data_origin/$', views.program_set_data_origin, name='set_data_origin_program'),
    url(r'^program/(?P<pk>[0-9]+)/schedule/$', views.program_set_data_origin, name='set_program_schedule'),
]

rl_proto2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required

from events.views import events

from integrations.salesforce.settings import (
    SALESFORCE_PROD_AUTH_URL,
    SALESFORCE_SANDBOX_AUTH_URL
    )


urlpatterns = [
    url(r'^', include('program_manager.urls'), name='programs'),

    url(r'^events\.json$', events),

    url(r'^analytics/', include('qscore.urls'), name='analytics'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^notifications/', include('notifications.urls'),
        name='notifications'),
    url(r'^payments/', include('payments.urls'), name='payments'),
    url(r'^reports/', include('reports.urls'), name='reports'),
    url(r'^api/', include('api.urls'), name='api'),
    url(r'^field_mapper/', include('field_mapper.urls',
        namespace='field_mapper')),
    url(r'^salesforce/', include('integrations.salesforce.urls', namespace='salesforce')),
    url(r'^welcome/$',
        login_required(TemplateView.as_view(template_name='welcome.html')),
        name='welcome'),

    # Incoming Oauth Redirects
    url(r'^oauth/', include('integrations.oauth'), name='oauth'),

    # Outgoing Oauth Redirects
    url(
        r'^salesforce_auth/$',
        RedirectView.as_view(url=SALESFORCE_PROD_AUTH_URL, permanent=False),
        name='salesforce_auth_request'
        ),
    url(
        r'^salesforce_sandbox/$',
        RedirectView.as_view(url=SALESFORCE_SANDBOX_AUTH_URL, permanent=False),
        name='salesforce_sandbox_auth_request'
        ),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^djangojs/', include('djangojs.urls')),
]

program_manager/models.py
import datetime
import uuid

from annoying.fields import AutoOneToOneField

from django.db import models
from django.utils.functional import cached_property

from celery.result import AsyncResult
from polymorphic import PolymorphicModel

import jsonfield

from accounts.models import CustomUser as CustomUser
from events.models import EventSourceMixin
from integrations.models import ExternalTable, ExternalField, Source, FileSource
from program_manager.choices import *
from program_manager import managers
from program_manager.signals import program_end, program_start, program_begin
from project_utils.models import SerializableModelMixin, ModelDiffMixin


class Program(ModelDiffMixin, EventSourceMixin, SerializableModelMixin, PolymorphicModel):
    """A generic job that contains a connected system (e.g. Salesforce), some
    defined actions and some granular settings."""

    user = models.ForeignKey(CustomUser)
    source = models.ForeignKey(Source, null=True, related_name='programs')
    created = models.DateTimeField(auto_now_add=True)
    last_run = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=256, null=True, blank=False)
    status = models.CharField(max_length=256, choices=STATUSES, default='CREA')
    data_origin = models.CharField(max_length=32, default='SALESFORCE', null=True, blank=True, choices=PROGRAM_SOURCES)
    table_schema = models.ForeignKey(ExternalTable, null=True)
    dedupe = models.BooleanField(default=True)
    analyze_only = models.BooleanField(default=False)
    location_optimization = models.BooleanField(default=False)
    contacts_normalization = models.BooleanField(default=True)
    junk_removal = models.BooleanField(default=True)
    tags = models.CharField(max_length=2048, null=True, blank=True)
    pre_backup_url = models.URLField(max_length=256, null=True, blank=True)
    post_run_url = models.URLField(max_length=256, null=True, blank=True)
    progress = models.PositiveSmallIntegerField(default=0)
    current_activity_description = models.CharField(max_length=256, null=True, blank=False)
    schedule_enabled = models.BooleanField(default=False)
    schedule_day = models.CharField(max_length=64, null=True, blank=False, default=DAYS_OF_WEEK[0][0], choices=DAYS_OF_WEEK)
    schedule_hour = models.TimeField(null=True, blank=False)
    resume_data = jsonfield.JSONField(null=True, blank=True)
    # # Person Info Optimization Options
    # person_name_proper_case = models.BooleanField(default=True)
    # # Company Info Optimization Options
    # address_optimize = models.BooleanField(default=True)
    # phone_optimize = models.BooleanField(default=True)

    objects = managers.ProgramManager()

    class Meta:
        ordering = ['-created']

    def __init__(self, *args, **kwargs):
        super(Program, self).__init__(*args, **kwargs)
        self.data_source = None

    def __unicode__(self):
        return self.name or 'unnamed'

    def save(self, *args, **kwargs):
        if not self.name:
            self.set_temp_name()

        has_changed = self.has_changed
        super(Program, self).save(*args, **kwargs)

        if has_changed:
            self.emit('program_changed')

    def begin(self, analyse_only=False):
        from qscore.models import QualityScore
        from program_manager import tasks as program_manager_tasks
        self.analyze_only = analyse_only

        # reset data urls
        self.pre_backup_url = ''
        self.post_run_url = ''

        self.status = 'RUN'
        self.save()

        QualityScore.objects.create(program=self)
        self.start_job(program_manager_tasks.run_program, self.pk)

        program_begin.send(None, program=self)

    def run(self):
        if isinstance(self.source, FileSource):
            self.analyze_only = True

        self.status = 'RUN'

        self.last_run = datetime.datetime.now()
        self.save()

        program_start.send(None, program=self)

        self.data_source = self.source.setup_data_source(self)
        self.data_source.launch()

        post_run_writer = self.data_source.get_writer('PostRunWriter')

        self.refresh_from_db()
        self.pre_backup_url = self.data_source.s3_backup_url
        self.post_run_url = post_run_writer.post_run_url
        self.status = 'COMPL'
        self.save()

        program_end.send(None, program=self, result=post_run_writer.result)

    @cached_property
    def count_records(self):
        return self.source.count_records(self)

    @cached_property
    def latest_report(self):
        return self.reports.order_by('date_created').last()

    @property
    def get_cname(self):
        """Returns the class name of the current Program"""
        pdict = {
            'ListImportProgram': 'List Import',
            'BatchProgram': 'Database Program',
        }
        return str(pdict[self.__class__.__name__])

    @property
    def get_program_icon(self):
        """Returns the appropriate icon for the current program"""
        icon_dict = {
            'ListImportProgram': 'fa-file-excel-o',
            'BatchProgram': 'fa-database',
        }
        return str(icon_dict[self.__class__.__name__])

    def start_job(self, task, *args, **kwargs):
        return Job.start(self, task, *args, **kwargs)

    def cancel_current_job(self):
        self.job_set.latest('id').cancel()

    def pause(self):
        self.job_set.latest('id').pause()
        self.status = 'PAUSE'
        self.save()

    def get_current_quality_score(self):
        """Returns the most recently calculated Quality Score"""
        qs = self.get_all_quality_scores()
        return qs[0] if qs else None

    def get_all_quality_scores(self):
        """Returns the most recently calculated Quality Score"""
        return self.quality_scores.all().order_by('-id')

    def get_table_filters(self):
        """Returns all TableFilter objects related to Program"""
        return self.tablefilter_set.all()

    def get_field_filters(self):
        """Returns all FieldFilter objects related to Program"""
        return self.fieldfilter_set.all()

    def get_dup_match_rules(self):
        """Returns all DupMatchRule objects related to Program"""
        return self.dupmatchrule_set.all()

    def get_surviving_record_rules(self):
        """Returns all SurvivingRecordRule objects related to Program"""
        return self.survivingrecordrule_set.all()

    def get_surviving_value_rules(self):
        """Returns all SurvivingValueRule objects related to Program"""
        return self.survivingvaluerule_set.all()

    @property
    def is_running(self):
        return self.status == 'RUN'

    def set_temp_name(self, save=False):
        self.name = 'Program %s' % str(uuid.uuid4())[:8]

        if save:
            self.save()


class Job(models.Model):
    """ Represents a job that is downloading, transforming or updating data as
    part of a Program."""

    program = models.ForeignKey(Program)
    name = models.CharField(max_length=256)
    progress = models.PositiveSmallIntegerField(default=0) # as a percentage
    task_id = models.CharField(max_length=128, unique=True)
    status = models.CharField(max_length=128, choices=JOB_STATUSES, default='PENDING')
    paused = models.BooleanField(default=False)

    @staticmethod
    def start(program, task, *args, **kwargs):
        result = task.delay(*args, **kwargs)
        name = '%s.%s' % (task.__module__, task.__name__)
        job = program.job_set.create(task_id=result.id, name=name)
        job.celery_task = result
        return job

    @staticmethod
    def get(task_id):
        return Job.objects.get(task_id=task_id)

    def __init__(self, *args, **kwargs):
        super(Job, self).__init__(*args, **kwargs)
        self.celery_task = None

    def __unicode__(self):
        return '%s (%s)' % (self.id, self.name)

    def get_celery_task(self):
        if not self.celery_task:
            self.celery_task = AsyncResult(self.task_id)
        return self.celery_task

    def update_from_task(self):
        self.status = self.get_celery_task().state
        self.save()

    def pause(self):
        self.get_celery_task().revoke(terminate=True, signal='SIGABRT')

    def cancel(self):
        self.get_celery_task().revoke(terminate=True)

    def resume(self):
        self.paused = False
        self.save()

    def update_progress(self, progress):
        self.progress = progress
        self.save()

    def is_finished(self):
        return self.get_celery_task().finished()


class TableFilter(models.Model):
    """
    A table in a connected system.  Tables can be dynamically loaded but
    in initial versions we will hard-code available tables and present these
    table options based on the connected system.
    """

    program = models.ForeignKey(Program, null=True, blank=True)
    table_name = models.CharField(max_length=256)  # ex. 'LEAD'


class FieldFilter(models.Model):
    """
    A field in a connected system and corresponding values that allow the
    user to determine a subset of their records.

    program: the related program
    field: field to filter on from a database table schema
    operator: the appropriate operator based on field type (e.g. >, <, =, older than)
    field_value: a single value or comma-separated values that would make the
    filter true
   """

    program = models.ForeignKey(Program, null=True, blank=False)
    field = models.ForeignKey(ExternalField)
    operator = models.CharField(max_length=256, default='=', choices=TEXT_OPERATORS+NUM_OPERATORS+DATETIME_OPERATORS+BOOL_OPERATORS)
    field_value = models.CharField(max_length=256, null=True, blank=True)


# class DateFieldFilter(FieldFilter):
#     operator = models.CharField(max_length=256, choices=DATETIME_OPERATORS)
#     value = models.DateField()


class DupMatchRule(models.Model):
    priority = models.IntegerField()
    program = models.ForeignKey(Program, null=True, blank=True)

rl_proto2/templates/program_manager/analysis_confirm.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}


<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h3 class="subtle_header">New analysis {% trans 'program' %}</h3>
  </div>
  <!--<div class="col-md-5" align="right" >
      <div class="btn-group btn-lg" role="group">
        <a href="{% url 'analysis_select' %}" class="btn btn-lg btn-default ">1</a>
        <a href="{% url 'analysis_confirm' %}" class="btn btn-lg btn-default active">2</a>
      </div>
  </div>-->
</div>
<br>
<div class="row">
    <div class="col-md-8 col-md-offset-2 well">
        <!-- nested rows & columns -->
        <div class="row">
            <div class="col-md-12" align="center">
                <h3>Begin Analysis {% trans 'Program' %}?</h3>
                <p>Ready to begin your data analysis?</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2" align="center">
                <a href="#" class="btn btn-lg btn-default" style="margin:20px">No, cancel analysis
                <a href="#" class="btn btn-lg btn-success" style="margin:20px">Yes, begin analysis</a>
            </div>
        </div>
        <!-- / nested rows & columns -->
    </div>
</div>
<br>


{% endblock %}

rl_proto2/templates/program_manager/analysis_select.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}
<br>
<br>
<br>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="row">
            <div class="col-md-6">
            <h5>I want to work on...</h5>
            <br>
            <div class="form-group">
                <select class="form-control" rows="5" id="comment">
                  <option selected value="csv" >a CSV File</option>
                  <option value="salesforce" >Salesforce Records</option>
                  <option value="marketo">Marketo Records</option>
                </select>
            </div>
            <div class="col-md-6">

            </div>
          </div>
          <div class="col-sm-6" style="height:250px">
              <div class="row" align="center">
                  <br>
                  <br>
                  <br>
                  <a href="#" class="btn btn-lg btn-primary btn-block" style="margin-left:30px"><i class="fa fa-upload"></i> Upload File</a>
              </div>
          </div>
          <!-- <div class="col-sm-6 well well-sm">
              <a href="#" class="active btn btn-default">Campaigns</a>
              <a href="#" class="btn btn-default">Users</a>
              <br>
              <br>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search..." id="email">
              </div>
              <div class="checkbox">
                <label><input type="checkbox" value="">CA World 2015</label>
              </div>
              <div class="checkbox">
                <label><input type="checkbox" value="">Cloud Computing World</label>
              </div>
              <div class="checkbox disabled">
                <label><input type="checkbox" value="">Gartner Summit</label>
              </div>
          </div> -->
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12" align="center">
        <a href="{% url 'analysis_confirm' %}" class="btn btn-lg btn-success">Continue</a>
    </div>
</div>


{% endblock %}

rl_proto2/templates/program_manager/batch_confirm.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block layout %}


    <div class="row">
        <div class="col-lg-4 col-md-5 col-sm-7 col-xs-8 col-lg-offset-3 col-md-offset-2 col-sm-offset-1 col-xs-offset-0">
            <h3>Step 3: Confirm & Run</h3>
        </div>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4" align="right">
            <div class="btn-group btn-lg" role="group">
                <a href="{% url 'batch_select' %}?pk={{ object.pk }}" class="btn btn-lg btn-default ">1</a>
                <a href="{% url 'select_actions' object.pk %}" class="btn btn-lg btn-default">2</a>
                <a href="{% url 'batch_confirm' object.pk %}" class="btn btn-lg btn-default active">3</a>
            </div>
        </div>
    </div>
    <hr>
    <br>
    <br>
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-12 col-lg-offset-3 col-md-offset-2 col-sm-offset-1 col-xs-offset-0">
            <div class="row">
                <div class="col-xs-12">
                    <form action="{% url 'batch_confirm' object.pk %}" method="POST" role="form"
                          class="form-horizontal" id="program-name-form">
                        {% csrf_token %}

                        <input type="hidden" name="run_now" value="off" />

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2">
                                {% if form.name.errors %}
                                    <div class="has-error">
                                        <label class="control-label" for="inputError">{{ form.name.errors.as_text }}</label>
                                        {% render_field form.name class+="form-control" placeholder=_("Program name") %}
                                    </div>
                                {% else %}
                                    {% render_field form.name class+="form-control" placeholder=_("Program name") %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 program-edit-button-container" align="center">
                                <a href="{% url 'program_list' %}" class="btn btn-lg btn-default">Cancel</a>
                                <button class="btn btn-lg btn-primary" id="run-later">
                                    Save &amp; Run Later
                                </button>
                                <button class="btn btn-lg btn-success" id="run-now">
                                    Save &amp; Run Now
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        $('#run-now').click(function(e) {
            $('input[name="run_now"]').val('on');
            $('#program-name-form').submit();
        });

        $('#run-later').click(function(e) {
            $('input[name="run_now"]').val('');
            $('#program-name-form').submit();
        });
    </script>

{% endblock %}

rl_proto2/templates/program_manager/batch_select.html
{% extends 'base.html' %}

{% load i18n static widget_tweaks date_utils %}

{% block layout %}
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h3>Select a Data Set</h3>
  </div>
  <div class="col-md-5" align="right" >
{#      {% include 'includes/batch_program_button_group.html' %}#}
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h5>Select a Table</h5>
        <!-- For each available table... -->
            <div class="row">
                <div class="col-sm-6">
                    <div class="checkbox">
                      <label><input type="checkbox" value="" checked disabled>Leads</label>
                    </div>
                    <div class="checkbox">
                      <label><input type="checkbox" value="" disabled>Contacts</label>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="checkbox disabled">
                      <label><input type="checkbox" value="" disabled>Accounts</label>
                    </div>
                    <div class="checkbox">
                      <label><input type="checkbox" value="" disabled>Opportunities</label>
                    </div>
                </div>
            </div>
      </div>
      <div class="col-md-4">
        <h5>Select a Database</h5>
        <br>
        <div class="form-group">
          <select class="form-control" disabled>
            <option selected value="salesforce" >Salesforce</option>
            <option value="marketo">Marketo</option>
            <option value="custom_db">ERP System</option>
          </select>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h5>Add Filters</h5>
        <div class="row">
          <div class="col-sm-11">
            {% if not field_filters %}
            <p>No filters selected</p>
            {% else %}
                {% for i in field_filters %}
                    <form action="{% url 'delete_fieldfilter' i.pk %}" method="POST">
                        <div class="alert alert-dismissible label-primary program-filter">
                            <button class="close" type="submit">
                                <span>&times;</span>
                            </button>
                            <i>{{ i.field.get_label }}</i>
                            {{ i.get_operator_display }}
                            {% if i.field.type == 'datetime' or i.field.type == 'date' %}
                                {{ i.field_value|parse_datetime|date:"m/d/Y" }}  &nbsp;&nbsp;&nbsp;
                            {% else %}
                                {{ i.field_value }}  &nbsp;&nbsp;&nbsp;
                            {% endif %}
                            {% csrf_token %}
                        </div>
                    </form>
                {% endfor %}
            {% endif %}
          </div>
        </div>
        <br>
        <div class="row" align="center">
          <a href="#" data-toggle="modal" data-target="#FiltersModal" class="btn btn-sm btn-default">Add a Filter</a>
        </div>
      </div>
      <div class="col-md-4">
        <h5>Record Count</h5>
        <br>
        <button class="btn btn-default btn-lg btn-link record-count" disabled><span class="count"></span><i class="fa fa-refresh" style="margin-left:10px"></i></button>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-12 program-edit-button-container" align="center">
    <a href="{% url 'program_list' %}" class="btn btn-lg btn-default">Cancel</a>
    <a href="{% url 'program_details' program.pk %}" class="btn btn-lg btn-success">Continue</a>
  </div>
</div>

<!-- Filters Modal -->
<div class="modal fade" id="FiltersModal" tabindex="-1" role="dialog" aria-labelledby="FiltersModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="FiltersModalLabel">Add a Filter</h4>
      </div>

      <form method="POST" action="{% url 'batch_select' %}?pk={{ program.pk }}">
        {% csrf_token %}
        <div class="modal-body">
          <table class="table well">
            {{ form.non_field_errors }}
            <thead>
              <tr>
                <td>Field Name</td>
                <td>Operator</td>
                <td class="value-column">Value</td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  {{ form.field | set_data:"live-search:true" | add_class:"selectpicker" }}
                </td>
                <td>
                  {{ form.operator }}
                </td>
                <td class="value-column">
                  {{ form.field_value }}
                </td>
              </tr>
              <tr>
                <td>
                  {% if form.field.errors %}
                  <div class="alert alert-danger">
                    {{ form.field.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
                <td>
                  {% if form.operator.errors %}
                  <div class="alert alert-danger">
                    {{ form.operator.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
                <td>
                  {% if form.field_value.errors %}
                  <div class="alert alert-danger">
                    {{ form.field_value.errors.as_text }}
                  </div>
                  {% endif %}
                </td>
              </tr>
            </tbody>
          </table>

          <div class="modal-footer">
            <button type="submit" class="btn btn-success">Add this filter</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script type='text/javascript'>
    var type_table = {{ type_table | safe }};
    var unary_operators = {{ unary_operators | safe }};
    $(document).ready(function () {
      /* open modal if there are any errors in the form */
      {% if form.errors %}
      $('#FiltersModal').modal('show');
      {% endif %}
      filter_operators(type_table, unary_operators);
      /* load count */
      !function(btn){
        var count = btn.find('.count');

        function loadCount() {
          btn.attr('disabled', true);
          count.html('Calculating…');

          $.ajax({
            url: '{% url "count_data" program.pk %}',
            dataType: 'json',
            success: function(data){
              count.html(numberWithCommas(data.count));
            },
            error: function(data){
              try {
                var error = JSON.parse(data.responseText);

                if (error.type == 'salesforceerror') {
                    alert('Error code: ' + error.data.errorCode + '\n' + error.data.message);
                }
                else if (error.type == 'connectionerror') {
                    alert('An error occurred when estabilishing a connection with the remote server.\nPossible cause: the remote server is in maintenance.');
                }

              } catch (e) {}

              count.html('Error');
            },
            complete: function(){
              btn.unbind('fade-cycle', fadeCycle);
              btn.removeAttr('disabled');
              btn.removeAttr('data-fade-cycle');
            }
          });

          // fade-cycle
          btn.bind('fade-cycle', fadeCycle);
          btn.trigger('fade-cycle');
        }

        function fadeCycle() {
          $(this).fadeOut('fast', function(){
            $(this).fadeIn('slow', function(){
              $(this).trigger('fade-cycle');
            });
          });
        }

        function numberWithCommas(x) {
          // http://stackoverflow.com/a/2901298/639465
          var parts = x.toString().split(".");
          parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
          return parts.join(".");
        }

        btn.click(loadCount);

        loadCount.apply(btn.get(0));

      }($('.record-count'));
    });
</script>

{% endblock %}

rl_proto2/templates/program_manager/deduperule_list.html
{% for element in elements %}
<tr>
  <td style="width: 35%">{{ element.field.get_label }}</td>
  <td style="width: 60%">{{ element.get_rule_display }}</td>
  <td style="vertical-align: middle;">
    <form class="delete-form" method="POST" action={% url 'delete_dupmatchrule' element.pk %}>
      {% csrf_token %}
      <button type="submit">
        <i class="fa fa-close text-default"></i>
      </button>
    </form>
  </td>
</tr>
{% endfor %}

rl_proto2/templates/program_manager/no_oauth.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block layout %}
<br>
<br>
<br>
<br>
<br>
<div class="row">
  <div class="col-md-12" align="center">
    <h5>It looks like you haven't added a connection to a data source yet, {{ user.first_name }}.
      Let's fix that!</h5>
    <a href="{% url 'accounts:connections' %}" class="btn btn-lg btn-warning">Add a connection</a>
  </div>
</div>
{% endblock %}